### ISSUE TITLE
About the training code 

### ISSUE THREAD

**Issue by aboyandaworld** [KUIS-AI-Tekalp-Research-Group/video-compression#3]
Thank you for your outstanding contribution! We intend to reproduce your model,but we can not figure out some details in the training.Could you share the training script?

**Comment by aboyandaworld** [comment]
I am sorry. I mean the training code of LHBDC.

**Comment by makinyilmaz** [comment]
Thank you for your interest. I will be sharing the training script in a few hours.

**Comment by aboyandaworld** [comment]
Hello,author. I hope you are doing well. I previously reached out to you regarding the training code and was expecting a response within a few hours. However, it has been three days now, and I wanted to inquire if there has been any progress. If you have encountered any issues or need more time, please let me know. Thank you very much for your assistance!

**Comment by makinyilmaz** [comment]
I uploaded the training code for a single lambda value under LHBDC. The code was written a couple of years ago. So if you encounter an issue please feel free to open another issue. For now I am closing this one
