### ISSUE TITLE
training code and pretrained model request

### ISSUE THREAD

**Issue by topriss** [KUIS-AI-Tekalp-Research-Group/video-compression#4]
Thank you for the great works!

We'd like to test and reproduce the result in "FLEXIBLE-RATE LEARNED HIERARCHICAL BI-DIRECTIONAL VIDEO COMPRESSION WITH MOTION REFINEMENT AND FRAME-LEVEL BIT ALLOCATION", but the link to the pretrained model seems to be limited (requiring access permission). Would you please open the access to the public ?

Also, there hasn't been a training script for this work. Would you please share a training script for training the flexible-rate model ?

Any help would be greatly appreciated. Many thanks.

**Comment by erenovic** [comment]
Hello @topriss, sorry for the delay in response. Thank you for warning about the access permission of the model weights. The link should not require access grant anymore. The training script will be shared in the future.
