### ISSUE TITLE
Hello，questions from beginners

### ISSUE THREAD

**Issue by luocha0107** [KUIS-AI-Tekalp-Research-Group/video-compression#5]
Hello, I am a video codec beginner based on deep learning, according to my understanding should be input uncompressed video into the network, and then output compressed video, why many networks only output psnr and ssim or pictures? And how do I train my own model? looking forward to your reply.

**Comment by makinyilmaz** [comment]
Hello, you may check out example codes for training compression networks at _compressai_ web page. I also recommend to check out the literature on learned image and video compression for better understanding.
